// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBROIkHKuOri1m17uRrKJqB-WrPOolMS0M',
    appId: '1:836724893984:web:6f77d085ebfba337990f45',
    messagingSenderId: '836724893984',
    projectId: 'royaldoor86-e6489',
    authDomain: 'royaldoor86-e6489.firebaseapp.com',
    databaseURL: 'https://royaldoor86-e6489-default-rtdb.firebaseio.com',
    storageBucket: 'royaldoor86-e6489.firebasestorage.app',
    measurementId: 'G-250YCPKS8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG1zLTl2gjJBOVlRzRtOUcfHeshJzasnA',
    appId: '1:836724893984:android:42c6fc1e086ec878990f45',
    messagingSenderId: '836724893984',
    projectId: 'royaldoor86-e6489',
    databaseURL: 'https://royaldoor86-e6489-default-rtdb.firebaseio.com',
    storageBucket: 'royaldoor86-e6489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_xf5jJQ0QdxZdOHBaCrZbQ2avNT2ujI',
    appId: '1:836724893984:ios:9d336f8cd2dfb9ac990f45',
    messagingSenderId: '836724893984',
    projectId: 'royaldoor86-e6489',
    databaseURL: 'https://royaldoor86-e6489-default-rtdb.firebaseio.com',
    storageBucket: 'royaldoor86-e6489.firebasestorage.app',
    androidClientId: '836724893984-25mme0cunr79t67sehe7d0ohkrj8tt0j.apps.googleusercontent.com',
    iosClientId: '836724893984-pu9oc09a8ocltc811hjaoupnr5gkqco4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_xf5jJQ0QdxZdOHBaCrZbQ2avNT2ujI',
    appId: '1:836724893984:ios:9d336f8cd2dfb9ac990f45',
    messagingSenderId: '836724893984',
    projectId: 'royaldoor86-e6489',
    databaseURL: 'https://royaldoor86-e6489-default-rtdb.firebaseio.com',
    storageBucket: 'royaldoor86-e6489.firebasestorage.app',
    androidClientId: '836724893984-25mme0cunr79t67sehe7d0ohkrj8tt0j.apps.googleusercontent.com',
    iosClientId: '836724893984-pu9oc09a8ocltc811hjaoupnr5gkqco4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBROIkHKuOri1m17uRrKJqB-WrPOolMS0M',
    appId: '1:836724893984:web:909584b4dc5e4534990f45',
    messagingSenderId: '836724893984',
    projectId: 'royaldoor86-e6489',
    authDomain: 'royaldoor86-e6489.firebaseapp.com',
    databaseURL: 'https://royaldoor86-e6489-default-rtdb.firebaseio.com',
    storageBucket: 'royaldoor86-e6489.firebasestorage.app',
    measurementId: 'G-VW49NGSSV3',
  );

}