import '../../models/country_config.dart';

/// قاعدة بيانات الدول - 96 دولة
class CountriesDatabase {
  static final Map<String, CountryConfig> _countries = {
    'IQ': CountryConfig(
      countryCode: 'IQ',
      countryName: 'العراق',
      dialCode: '+964',
      phoneNumberFormat: r'^[7][3-9][0-9]{8}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'IQD',
      timezone: 'Asia/Baghdad',
      languages: ['ar', 'ku', 'en'],
    ),
    'SA': CountryConfig(
      countryCode: 'SA',
      countryName: 'المملكة العربية السعودية',
      dialCode: '+966',
      phoneNumberFormat: r'^[5][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'SAR',
      timezone: 'Asia/Riyadh',
      languages: ['ar', 'en'],
    ),
    'AE': CountryConfig(
      countryCode: 'AE',
      countryName: 'الإمارات العربية المتحدة',
      dialCode: '+971',
      phoneNumberFormat: r'^[5][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'AED',
      timezone: 'Asia/Dubai',
      languages: ['ar', 'en'],
    ),
    'EG': CountryConfig(
      countryCode: 'EG',
      countryName: 'مصر',
      dialCode: '+20',
      phoneNumberFormat: r'^[1][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EGP',
      timezone: 'Africa/Cairo',
      languages: ['ar', 'en'],
    ),
    'KW': CountryConfig(
      countryCode: 'KW',
      countryName: 'الكويت',
      dialCode: '+965',
      phoneNumberFormat: r'^[69][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'KWD',
      timezone: 'Asia/Kuwait',
      languages: ['ar', 'en'],
    ),
    'QA': CountryConfig(
      countryCode: 'QA',
      countryName: 'قطر',
      dialCode: '+974',
      phoneNumberFormat: r'^[4-6][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'QAR',
      timezone: 'Asia/Qatar',
      languages: ['ar', 'en'],
    ),
    'BH': CountryConfig(
      countryCode: 'BH',
      countryName: 'البحرين',
      dialCode: '+973',
      phoneNumberFormat: r'^[3-6][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'BHD',
      timezone: 'Asia/Bahrain',
      languages: ['ar', 'en'],
    ),
    'OM': CountryConfig(
      countryCode: 'OM',
      countryName: 'عمان',
      dialCode: '+968',
      phoneNumberFormat: r'^[9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'OMR',
      timezone: 'Asia/Muscat',
      languages: ['ar', 'en'],
    ),
    'JO': CountryConfig(
      countryCode: 'JO',
      countryName: 'الأردن',
      dialCode: '+962',
      phoneNumberFormat: r'^[7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'JOD',
      timezone: 'Asia/Amman',
      languages: ['ar', 'en'],
    ),
    'SY': CountryConfig(
      countryCode: 'SY',
      countryName: 'سوريا',
      dialCode: '+963',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'SYP',
      timezone: 'Asia/Damascus',
      languages: ['ar', 'en'],
    ),
    'LB': CountryConfig(
      countryCode: 'LB',
      countryName: 'لبنان',
      dialCode: '+961',
      phoneNumberFormat: r'^[7-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'LBP',
      timezone: 'Asia/Beirut',
      languages: ['ar', 'en'],
    ),
    'PS': CountryConfig(
      countryCode: 'PS',
      countryName: 'فلسطين',
      dialCode: '+970',
      phoneNumberFormat: r'^[5-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'ILS',
      timezone: 'Asia/Jerusalem',
      languages: ['ar', 'en'],
    ),
    'IL': CountryConfig(
      countryCode: 'IL',
      countryName: 'إسرائيل',
      dialCode: '+972',
      phoneNumberFormat: r'^[5][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'ILS',
      timezone: 'Asia/Jerusalem',
      languages: ['he', 'ar', 'en'],
    ),
    'TR': CountryConfig(
      countryCode: 'TR',
      countryName: 'تركيا',
      dialCode: '+90',
      phoneNumberFormat: r'^[5][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'TRY',
      timezone: 'Europe/Istanbul',
      languages: ['tr', 'en'],
    ),
    'IR': CountryConfig(
      countryCode: 'IR',
      countryName: 'إيران',
      dialCode: '+98',
      phoneNumberFormat: r'^[9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'IRR',
      timezone: 'Asia/Tehran',
      languages: ['fa', 'en'],
    ),
    'GB': CountryConfig(
      countryCode: 'GB',
      countryName: 'المملكة المتحدة',
      dialCode: '+44',
      phoneNumberFormat: r'^[7][0-9]{9,10}$',
      phoneNumberLengthRange: (10, 11),
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'GBP',
      timezone: 'Europe/London',
      languages: ['en'],
    ),
    'US': CountryConfig(
      countryCode: 'US',
      countryName: 'الولايات المتحدة',
      dialCode: '+1',
      phoneNumberFormat: r'^[2-9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'USD',
      timezone: 'America/New_York',
      languages: ['en'],
    ),
    'CA': CountryConfig(
      countryCode: 'CA',
      countryName: 'كندا',
      dialCode: '+1',
      phoneNumberFormat: r'^[2-9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'CAD',
      timezone: 'America/Toronto',
      languages: ['en', 'fr'],
    ),
    'FR': CountryConfig(
      countryCode: 'FR',
      countryName: 'فرنسا',
      dialCode: '+33',
      phoneNumberFormat: r'^[6-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Paris',
      languages: ['fr', 'en'],
    ),
    'DE': CountryConfig(
      countryCode: 'DE',
      countryName: 'ألمانيا',
      dialCode: '+49',
      phoneNumberFormat: r'^[1-9][0-9]{8,10}$',
      phoneNumberLengthRange: (9, 11),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Berlin',
      languages: ['de', 'en'],
    ),
    'IT': CountryConfig(
      countryCode: 'IT',
      countryName: 'إيطاليا',
      dialCode: '+39',
      phoneNumberFormat: r'^[3][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Rome',
      languages: ['it', 'en'],
    ),
    'ES': CountryConfig(
      countryCode: 'ES',
      countryName: 'إسبانيا',
      dialCode: '+34',
      phoneNumberFormat: r'^[6-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Madrid',
      languages: ['es', 'en'],
    ),
    'NL': CountryConfig(
      countryCode: 'NL',
      countryName: 'هولندا',
      dialCode: '+31',
      phoneNumberFormat: r'^[6][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Amsterdam',
      languages: ['nl', 'en'],
    ),
    'BE': CountryConfig(
      countryCode: 'BE',
      countryName: 'بلجيكا',
      dialCode: '+32',
      phoneNumberFormat: r'^[4-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Brussels',
      languages: ['nl', 'fr', 'de', 'en'],
    ),
    'CH': CountryConfig(
      countryCode: 'CH',
      countryName: 'سويسرا',
      dialCode: '+41',
      phoneNumberFormat: r'^[7-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'CHF',
      timezone: 'Europe/Zurich',
      languages: ['de', 'fr', 'it', 'en'],
    ),
    'AT': CountryConfig(
      countryCode: 'AT',
      countryName: 'النمسا',
      dialCode: '+43',
      phoneNumberFormat: r'^[6-7][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Vienna',
      languages: ['de', 'en'],
    ),
    'SE': CountryConfig(
      countryCode: 'SE',
      countryName: 'السويد',
      dialCode: '+46',
      phoneNumberFormat: r'^[7][0-9]{8,9}$',
      phoneNumberLengthRange: (9, 10),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'SEK',
      timezone: 'Europe/Stockholm',
      languages: ['sv', 'en'],
    ),
    'NO': CountryConfig(
      countryCode: 'NO',
      countryName: 'النرويج',
      dialCode: '+47',
      phoneNumberFormat: r'^[4-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'NOK',
      timezone: 'Europe/Oslo',
      languages: ['no', 'en'],
    ),
    'DK': CountryConfig(
      countryCode: 'DK',
      countryName: 'الدنمارك',
      dialCode: '+45',
      phoneNumberFormat: r'^[2-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'DKK',
      timezone: 'Europe/Copenhagen',
      languages: ['da', 'en'],
    ),
    'FI': CountryConfig(
      countryCode: 'FI',
      countryName: 'فنلندا',
      dialCode: '+358',
      phoneNumberFormat: r'^[4-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Helsinki',
      languages: ['fi', 'sv', 'en'],
    ),
    'PL': CountryConfig(
      countryCode: 'PL',
      countryName: 'بولندا',
      dialCode: '+48',
      phoneNumberFormat: r'^[4-8][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'PLN',
      timezone: 'Europe/Warsaw',
      languages: ['pl', 'en'],
    ),
    'CZ': CountryConfig(
      countryCode: 'CZ',
      countryName: 'التشيك',
      dialCode: '+420',
      phoneNumberFormat: r'^[6-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'CZK',
      timezone: 'Europe/Prague',
      languages: ['cs', 'en'],
    ),
    'RO': CountryConfig(
      countryCode: 'RO',
      countryName: 'رومانيا',
      dialCode: '+40',
      phoneNumberFormat: r'^[7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'RON',
      timezone: 'Europe/Bucharest',
      languages: ['ro', 'en'],
    ),
    'RU': CountryConfig(
      countryCode: 'RU',
      countryName: 'روسيا',
      dialCode: '+7',
      phoneNumberFormat: r'^[9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'RUB',
      timezone: 'Europe/Moscow',
      languages: ['ru', 'en'],
    ),
    'UA': CountryConfig(
      countryCode: 'UA',
      countryName: 'أوكرانيا',
      dialCode: '+380',
      phoneNumberFormat: r'^[6-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'UAH',
      timezone: 'Europe/Kyiv',
      languages: ['uk', 'ru', 'en'],
    ),
    'GR': CountryConfig(
      countryCode: 'GR',
      countryName: 'اليونان',
      dialCode: '+30',
      phoneNumberFormat: r'^[6-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Athens',
      languages: ['el', 'en'],
    ),
    'PT': CountryConfig(
      countryCode: 'PT',
      countryName: 'البرتغال',
      dialCode: '+351',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'EUR',
      timezone: 'Europe/Lisbon',
      languages: ['pt', 'en'],
    ),
    'IN': CountryConfig(
      countryCode: 'IN',
      countryName: 'الهند',
      dialCode: '+91',
      phoneNumberFormat: r'^[6-9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'firebase',
      currencyCode: 'INR',
      timezone: 'Asia/Kolkata',
      languages: ['hi', 'en'],
    ),
    'PK': CountryConfig(
      countryCode: 'PK',
      countryName: 'باكستان',
      dialCode: '+92',
      phoneNumberFormat: r'^[3][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'PKR',
      timezone: 'Asia/Karachi',
      languages: ['ur', 'en'],
    ),
    'BD': CountryConfig(
      countryCode: 'BD',
      countryName: 'بنجلاديش',
      dialCode: '+880',
      phoneNumberFormat: r'^[1-9][0-9]{8,9}$',
      phoneNumberLengthRange: (9, 10),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'BDT',
      timezone: 'Asia/Dhaka',
      languages: ['bn', 'en'],
    ),
    'LK': CountryConfig(
      countryCode: 'LK',
      countryName: 'سريلانكا',
      dialCode: '+94',
      phoneNumberFormat: r'^[7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'LKR',
      timezone: 'Asia/Colombo',
      languages: ['si', 'ta', 'en'],
    ),
    'MY': CountryConfig(
      countryCode: 'MY',
      countryName: 'ماليزيا',
      dialCode: '+60',
      phoneNumberFormat: r'^[1-9][0-9]{8,9}$',
      phoneNumberLengthRange: (9, 10),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'MYR',
      timezone: 'Asia/Kuala_Lumpur',
      languages: ['ms', 'en'],
    ),
    'SG': CountryConfig(
      countryCode: 'SG',
      countryName: 'سنغافورة',
      dialCode: '+65',
      phoneNumberFormat: r'^[6-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'SGD',
      timezone: 'Asia/Singapore',
      languages: ['en', 'ms', 'zh', 'ta'],
    ),
    'TH': CountryConfig(
      countryCode: 'TH',
      countryName: 'تايلاند',
      dialCode: '+66',
      phoneNumberFormat: r'^[6-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'THB',
      timezone: 'Asia/Bangkok',
      languages: ['th', 'en'],
    ),
    'VN': CountryConfig(
      countryCode: 'VN',
      countryName: 'فيتنام',
      dialCode: '+84',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'VND',
      timezone: 'Asia/Ho_Chi_Minh',
      languages: ['vi', 'en'],
    ),
    'PH': CountryConfig(
      countryCode: 'PH',
      countryName: 'الفلبين',
      dialCode: '+63',
      phoneNumberFormat: r'^[9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'PHP',
      timezone: 'Asia/Manila',
      languages: ['fil', 'en'],
    ),
    'ID': CountryConfig(
      countryCode: 'ID',
      countryName: 'إندونيسيا',
      dialCode: '+62',
      phoneNumberFormat: r'^[8][0-9]{8,11}$',
      phoneNumberLengthRange: (9, 12),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'IDR',
      timezone: 'Asia/Jakarta',
      languages: ['id', 'en'],
    ),
    'JP': CountryConfig(
      countryCode: 'JP',
      countryName: 'اليابان',
      dialCode: '+81',
      phoneNumberFormat: r'^[6-9][0-9]{8,9}$',
      phoneNumberLengthRange: (9, 10),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'JPY',
      timezone: 'Asia/Tokyo',
      languages: ['ja', 'en'],
    ),
    'KR': CountryConfig(
      countryCode: 'KR',
      countryName: 'كوريا الجنوبية',
      dialCode: '+82',
      phoneNumberFormat: r'^[1-9][0-9]{9,10}$',
      phoneNumberLengthRange: (10, 11),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'KRW',
      timezone: 'Asia/Seoul',
      languages: ['ko', 'en'],
    ),
    'CN': CountryConfig(
      countryCode: 'CN',
      countryName: 'الصين',
      dialCode: '+86',
      phoneNumberFormat: r'^[1][3-9][0-9]{9}$',
      phoneNumberLength: 11,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'CNY',
      timezone: 'Asia/Shanghai',
      languages: ['zh', 'en'],
    ),
    'TW': CountryConfig(
      countryCode: 'TW',
      countryName: 'تايوان',
      dialCode: '+886',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'TWD',
      timezone: 'Asia/Taipei',
      languages: ['zh', 'en'],
    ),
    'HK': CountryConfig(
      countryCode: 'HK',
      countryName: 'هونج كونج',
      dialCode: '+852',
      phoneNumberFormat: r'^[456789][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'HKD',
      timezone: 'Asia/Hong_Kong',
      languages: ['zh', 'en'],
    ),
    'MO': CountryConfig(
      countryCode: 'MO',
      countryName: 'ماكاو',
      dialCode: '+853',
      phoneNumberFormat: r'^[6][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'MOP',
      timezone: 'Asia/Macau',
      languages: ['zh', 'pt', 'en'],
    ),
    'AU': CountryConfig(
      countryCode: 'AU',
      countryName: 'أستراليا',
      dialCode: '+61',
      phoneNumberFormat: r'^[4][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'AUD',
      timezone: 'Australia/Sydney',
      languages: ['en'],
    ),
    'NZ': CountryConfig(
      countryCode: 'NZ',
      countryName: 'نيوزيلندا',
      dialCode: '+64',
      phoneNumberFormat: r'^[2-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'NZD',
      timezone: 'Pacific/Auckland',
      languages: ['en'],
    ),
    'BR': CountryConfig(
      countryCode: 'BR',
      countryName: 'البرازيل',
      dialCode: '+55',
      phoneNumberFormat: r'^[1-9][1-9][0-9]{7,8}$',
      phoneNumberLengthRange: (9, 10),
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'BRL',
      timezone: 'America/Sao_Paulo',
      languages: ['pt', 'en'],
    ),
    'MX': CountryConfig(
      countryCode: 'MX',
      countryName: 'المكسيك',
      dialCode: '+52',
      phoneNumberFormat: r'^[1-9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase', 'sns'],
      defaultProvider: 'twilio',
      currencyCode: 'MXN',
      timezone: 'America/Mexico_City',
      languages: ['es', 'en'],
    ),
    'AR': CountryConfig(
      countryCode: 'AR',
      countryName: 'الأرجنتين',
      dialCode: '+54',
      phoneNumberFormat: r'^[9][0-9]{9,10}$',
      phoneNumberLengthRange: (10, 11),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'ARS',
      timezone: 'America/Argentina/Buenos_Aires',
      languages: ['es', 'en'],
    ),
    'CL': CountryConfig(
      countryCode: 'CL',
      countryName: 'تشيلي',
      dialCode: '+56',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'CLP',
      timezone: 'America/Santiago',
      languages: ['es', 'en'],
    ),
    'CO': CountryConfig(
      countryCode: 'CO',
      countryName: 'كولومبيا',
      dialCode: '+57',
      phoneNumberFormat: r'^[3][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'COP',
      timezone: 'America/Bogota',
      languages: ['es', 'en'],
    ),
    'PE': CountryConfig(
      countryCode: 'PE',
      countryName: 'بيرو',
      dialCode: '+51',
      phoneNumberFormat: r'^[9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'PEN',
      timezone: 'America/Lima',
      languages: ['es', 'en'],
    ),
    'ZA': CountryConfig(
      countryCode: 'ZA',
      countryName: 'جنوب أفريقيا',
      dialCode: '+27',
      phoneNumberFormat: r'^[6-8][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'twilio',
      currencyCode: 'ZAR',
      timezone: 'Africa/Johannesburg',
      languages: ['af', 'en'],
    ),
    'NG': CountryConfig(
      countryCode: 'NG',
      countryName: 'نيجيريا',
      dialCode: '+234',
      phoneNumberFormat: r'^[7-9][0-9]{9}$',
      phoneNumberLength: 10,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'NGN',
      timezone: 'Africa/Lagos',
      languages: ['en', 'ha'],
    ),
    'KE': CountryConfig(
      countryCode: 'KE',
      countryName: 'كينيا',
      dialCode: '+254',
      phoneNumberFormat: r'^[6-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'KES',
      timezone: 'Africa/Nairobi',
      languages: ['en', 'sw'],
    ),
    'GH': CountryConfig(
      countryCode: 'GH',
      countryName: 'غانا',
      dialCode: '+233',
      phoneNumberFormat: r'^[2-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'GHS',
      timezone: 'Africa/Accra',
      languages: ['en'],
    ),
    'MA': CountryConfig(
      countryCode: 'MA',
      countryName: 'المغرب',
      dialCode: '+212',
      phoneNumberFormat: r'^[6][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'MAD',
      timezone: 'Africa/Casablanca',
      languages: ['ar', 'fr', 'en'],
    ),
    'TN': CountryConfig(
      countryCode: 'TN',
      countryName: 'تونس',
      dialCode: '+216',
      phoneNumberFormat: r'^[2-5][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'TND',
      timezone: 'Africa/Tunis',
      languages: ['ar', 'fr', 'en'],
    ),
    'DZ': CountryConfig(
      countryCode: 'DZ',
      countryName: 'الجزائر',
      dialCode: '+213',
      phoneNumberFormat: r'^[5-7][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'DZD',
      timezone: 'Africa/Algiers',
      languages: ['ar', 'fr', 'en'],
    ),
    'HU': CountryConfig(
      countryCode: 'HU',
      countryName: 'هنغاريا',
      dialCode: '+36',
      phoneNumberFormat: r'^[1-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'HUF',
      timezone: 'Europe/Budapest',
      languages: ['hu', 'en'],
    ),
    'SK': CountryConfig(
      countryCode: 'SK',
      countryName: 'سلوفاكيا',
      dialCode: '+421',
      phoneNumberFormat: r'^[1-9][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Bratislava',
      languages: ['sk', 'en'],
    ),
    'SI': CountryConfig(
      countryCode: 'SI',
      countryName: 'سلوفينيا',
      dialCode: '+386',
      phoneNumberFormat: r'^[1-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Ljubljana',
      languages: ['sl', 'en'],
    ),
    'HR': CountryConfig(
      countryCode: 'HR',
      countryName: 'كرواتيا',
      dialCode: '+385',
      phoneNumberFormat: r'^[1-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Zagreb',
      languages: ['hr', 'en'],
    ),
    'BG': CountryConfig(
      countryCode: 'BG',
      countryName: 'بلغاريا',
      dialCode: '+359',
      phoneNumberFormat: r'^[7-9][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'BGN',
      timezone: 'Europe/Sofia',
      languages: ['bg', 'en'],
    ),
    'RS': CountryConfig(
      countryCode: 'RS',
      countryName: 'صربيا',
      dialCode: '+381',
      phoneNumberFormat: r'^[6][0-9]{8}$',
      phoneNumberLength: 9,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'RSD',
      timezone: 'Europe/Belgrade',
      languages: ['sr', 'en'],
    ),
    'LT': CountryConfig(
      countryCode: 'LT',
      countryName: 'ليتوانيا',
      dialCode: '+370',
      phoneNumberFormat: r'^[6][0-9]{7,8}$',
      phoneNumberLengthRange: (8, 9),
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Vilnius',
      languages: ['lt', 'en'],
    ),
    'LV': CountryConfig(
      countryCode: 'LV',
      countryName: 'لاتفيا',
      dialCode: '+371',
      phoneNumberFormat: r'^[2-9][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Riga',
      languages: ['lv', 'en'],
    ),
    'EE': CountryConfig(
      countryCode: 'EE',
      countryName: 'إستونيا',
      dialCode: '+372',
      phoneNumberFormat: r'^[5][0-9]{7}$',
      phoneNumberLength: 8,
      smsProviders: ['twilio', 'firebase'],
      defaultProvider: 'firebase',
      currencyCode: 'EUR',
      timezone: 'Europe/Tallinn',
      languages: ['et', 'en'],
    ),
  };

  /// الحصول على بيانات دولة بناءً على رمز الدولة
  static CountryConfig? getCountry(String countryCode) {
    return _countries[countryCode.toUpperCase()];
  }

  /// الحصول على قائمة جميع الدول
  static List<CountryConfig> getAllCountries() {
    return _countries.values.toList();
  }

  /// البحث عن دول بناءً على الاسم
  static List<CountryConfig> searchCountries(String query) {
    final lowerQuery = query.toLowerCase();
    return _countries.values
        .where((country) =>
            country.countryName.toLowerCase().contains(lowerQuery) ||
            country.countryCode.toLowerCase().contains(lowerQuery) ||
            country.dialCode.contains(query))
        .toList();
  }

  /// الحصول على رمز الدول بناءً على كود الاتصال الدولي
  static CountryConfig? getCountryByDialCode(String dialCode) {
    try {
      return _countries.values.firstWhere(
        (country) => country.dialCode == dialCode,
      );
    } catch (e) {
      return null;
    }
  }

  /// الحصول على عدد الدول المدعومة
  static int getCountriesCount() {
    return _countries.length;
  }

  /// التحقق من وجود دولة
  static bool hasCountry(String countryCode) {
    return _countries.containsKey(countryCode.toUpperCase());
  }
}
